name: gradleCI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

#      - name: Generate JaCoCo Badge
#        id: jacoco
#        uses: cicirello/jacoco-badge-generator@v2
#        with:
#          jacoco-csv-file: build/reports/jacoco/jacoco.csv
      - uses: actions/upload-artifact@v3
        with:
          name: JaCoCo_Report
          path: build/reports/jacoco/